kind: Service
apiVersion: v1
metadata:
  name: demowebapi
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: demowebapi
          image: "demo-webapi:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
      