kind: Service
apiVersion: v1
metadata:
  name: demowebapi
spec:
  selector:
    app: demowebapi
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demowebapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demowebapi
        tier: backend
        track: stable
    spec:
      containers:
        - name: demowebapi
          image: "demo-webapi"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
      