kind: Service
apiVersion: v1
metadata:
  name: demowebapi
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
        - name: demowebapi
          image: "workshoprrp.azurecr.io/demo-webapi:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: regcred 