version: '3.4'

services:
  webapp:
    image: demo-webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - webapi
    environment:
      ApiHost: "webapi"

  webapi:
    image: demo-webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

