kind: Service
apiVersion: v1
metadata:
  name: demowebapp
spec:
  selector:
    app: demowebapp
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp
  labels:
    app: demowebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demowebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: demowebapp
        tier: frontend
        track: stable
    spec:
      containers:
        - name: demowebapp
          image: "workshopdev/demo-webapp:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: ApiHost
              value: "demowebapi"
          ports:
            - name: http
              containerPort: 80
