apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
# Format for .dockerconfigjson (base64 encoded)
# {"auths":{"your.private.registry.example.com":{"username":"janedoe","password":"xxxxxxxxxxx","email":"jdoe@example.com","auth":"c3R...zE2"}}}
# Format for "auth:" = username:password (base64 encoded)
# (linux) echo 'string to encode' | base64 -w 1000
# (linux) echo 'string to decode' | base64 --decode
data:
  .dockerconfigjson: eyJhdXRocyI6eyJycnB0ZXN0LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJycnB0ZXN0IiwicGFzc3dvcmQiOiJUeHozb0Q2OUpYeEl0TD13ZnNMSHZaTHM0T2ZGSy9rVSIsImVtYWlsIjoibWVAdGhpcy5jb20iLCJhdXRoIjoiY25Kd2RHVnpkRHBVZUhvemIwUTJPVXBZZUVsMFREMTNabk5NU0haYVRITTBUMlpHU3k5clZRPT0ifX19


# CLI
# kubectl create secret docker-registry regcred --docker-server=rrptest.azurecr.io --docker-username=rrptest --docker-password=Txz3oD69JXxItL=wfsLHvZLs4OfFK/kU --docker-email=me@this.com